// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyuvhmjiadwbsypfbpfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dXZobWppYWR3YnN5cGZicGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1Njg4NTcsImV4cCI6MjA2MzE0NDg1N30.TxKPhiey5H2LCa2cqOzYYfjEJbQ_gJt4cPKGq5XA_lA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);